name: Test
on:
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'

      - name: Install dependencies
        run: bundle install

      - name: Test
        run: bundle exec rspec
